version: "3.8"
services:
    website:
      build:
          context: .          
          dockerfile: docker/Dockerfile
      image: ${APP_NAME}_website:${APP_VERSION}
      container_name: ${APP_NAME}_website_container
      ports:
          - "8080:80"   